name: Test Action

on:
  push:
    tags: ["*"]

jobs:
  print-hello:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]