name: Test Action

on:
  push:
    branches:
      - main

jobs:
  print-hello:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps: 
      - uses: actions/checkout@v3
      - name: Create a release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: MyReleaseMessage
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]