on:
  push:
    branches:
      - main

jobs:
  print-hello:
    runs-on: {{ matrix.os }}
    steps: 
      - run: echo "Hello world!"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]