name: Test Action

on:
  push:
    tags: ["*"]

jobs:
  print-hello:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps: 
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]